#!/bin/bash

# env=home,work
env=$1

if [ -z "$env" ]; then
  echo 'Environment argument required. (home/work)' && exit
fi

# Remove default files
echo '⚠️ Stow is unable to overwrite source files. You may have to remove defaults manually before running stow.'
read -p "Remove defaults? [y/n]"$'\n' -n 1 -r && echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  echo "⚠️ Skipped defaults removal..."
else
  # TODO: Add more? (expand a bit?)
  rm ~/.bashrc
fi

read -n 1 -p "Unstow (y/n)? " answer1
echo
if [[ $answer1 =~ ^[Yy]$ ]]; then
  echo 'Unstowing...'

  for stowDir in */; do
    echo "🗑️ Unstowing ${stowDir}"
    stow -D "$stowDir"

    if [ $? -eq 0 ]; then
      echo OK
    else
      echo FAIL
    fi
  done
fi

read -n 1 -p "Stow (y/n)? " answer2
echo
if [[ $answer2 =~ ^[Yy]$ ]]; then
  echo -e 'Stowing...'

  for stowDir in */; do
    stowDirPath="./${stowDir}${env}"
    if [ -d "$stowDirPath" ]; then
      cd "$stowDir" || exit
      echo "--> Stowing ${stowDir} for env '${env}'..."
      stow -vSt ~ "$env"
      cd - || exit
    else
      echo "--> Stowing ${stowDir} without env..."
      stow -vSt ~ "$stowDir"
    fi

    if [ $? -eq 0 ]; then
      echo OK
    else
      echo FAIL
    fi
  done
fi
