#!/bin/bash
# Full one tap installation script for everything

export DOTFILES=~/dotfiles

function installations () {
  cd "${DOTFILES}/installations" || exit
  for installation in ./*; do
    # 0 file is required stuff
    if [ $installation == "./0" ]; then
      ./"$installation" $1 && continue
    fi
    # Run all
    if [ $2 ]; then
      ./"$installation" $1 && continue
    fi
    # Prompt run
    read -p "Run installation: '${installation}'? [y/n]"$'\n' -n 1 -r && echo;
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      echo "Skipped installation..."
    else
      ./"$installation" $1
    fi
  done
  cd - || exit
}

function stowem () {
  cd "${DOTFILES}/dotstows" || exit
  ./stowem $1
  cd -
}

function postinstallations() {
  vim +'PlugInstall --sync' +qa
  echo "Ignore .vimrc erorrs, installed plugins restart vim!"
  # PLEASE FIX THIS EVENTUALLY
  echo "Tmux conf file Dos issue patch..."
  dos2unix ./dotstows/tmux/.tmux.conf
}

envs=("home" "work")
echo "Choose environment:"
select env in "${envs[@]}"; do
  case $env in
  "home")
    echo "Starting setup for 'home' environmment."
    break
    ;;
  "work")
    echo "Starting setup for 'work' environmment."
    break
    ;;
  esac
done

read -p "🔗 Run stows? [y/n] "$'\n' answer2
case ${answer2:0:1} in
    y|Y )
        stowem $env;
    ;;
    * )
        echo "Skipped stows..."
    ;;
esac


read -p "🚀 Run installations? [y/n/a]"$'\n' answer
case ${answer:0:1} in
    y|Y )
        installations $env; 
    ;;
    a|A )
        installations $env true;
    ;;
    * )
        echo "Skipped installations..."
    ;;
esac

read -p "⚙️ Run post-installations? [y/n] "$'\n' answer3
case ${answer3:0:1} in
    y|Y )
        postinstallations $env;
    ;;
    * )
        echo "Skipped post-installations..."
    ;;
esac
